# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confetti < Formula
  desc ""
  homepage "https://confetti-cms.com"
  version "0.5.3"

  on_macos do
    url "https://github.com/confetti-cms/client/releases/download/0.5.3/client_0.5.3_darwin_all.tar.gz"
    sha256 "0ccead92018299e11bc4ab8883fa5bf22049d168f4cf51f69c8ecc1ec89b354c"

    def install
      main: confetti
      id: confetti
      binary: confetti
      bin.install "confetti"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/confetti-cms/client/releases/download/0.5.3/client_0.5.3_linux_amd64.tar.gz"
      sha256 "37af33356e45b35533d1b5e04af9d4d387010886fc4618ae38a45041547f3dbd"

      def install
        main: confetti
        id: confetti
        binary: confetti
        bin.install "confetti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confetti-cms/client/releases/download/0.5.3/client_0.5.3_linux_arm64.tar.gz"
      sha256 "2c2d3fe0573e64684b63a77fd171c508134ffeba9de8993242a77200c34364e3"

      def install
        main: confetti
        id: confetti
        binary: confetti
        bin.install "confetti"
      end
    end
  end
end
