# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confetti < Formula
  desc ""
  homepage "https://confetti-cms.com"
  version "0.4.2"

  on_macos do
    url "https://github.com/confetti-cms/client/releases/download/0.4.2/client_0.4.2_darwin_all.tar.gz"
    sha256 "8534cddee6a85aa4fa7e69c9c2bfccea661d2eda1bf63a19a2788e1afc026b43"

    def install
      bin.install "client"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confetti-cms/client/releases/download/0.4.2/client_0.4.2_linux_arm64.tar.gz"
      sha256 "7f7f3e257c4326866bf093733474e839405cb0f2d769b147718e163e062b323f"

      def install
        bin.install "confetti"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/confetti-cms/client/releases/download/0.4.2/client_0.4.2_linux_amd64.tar.gz"
      sha256 "2021c6aff4d04a9b612b3e988820f97a3acf0453910c8e3805f5cc157ce6fbb3"

      def install
        bin.install "confetti"
      end
    end
  end
end
