# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conf < Formula
  desc ""
  homepage "https://confetti-cms.com"
  version "1.42.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/confetti-cms/conf/releases/download/1.42.0/conf_Darwin_x86_64.tar.gz"
      sha256 "0f9f83a0c85e0c6916ac8db3349a5c47d9d178314110a99c88570e08992255b0"

      def install
        bin.install "conf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/confetti-cms/conf/releases/download/1.42.0/conf_Darwin_arm64.tar.gz"
      sha256 "662099e0c8e3598404645fa113df60db41ee5ee74ed6680c19e6698f03ff2647"

      def install
        bin.install "conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/confetti-cms/conf/releases/download/1.42.0/conf_Linux_x86_64.tar.gz"
        sha256 "2cb7cd8111d9c6a53bdb5d296246a8c71860170f5eda4154603f9d3737556d0b"

        def install
          bin.install "conf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/confetti-cms/conf/releases/download/1.42.0/conf_Linux_arm64.tar.gz"
        sha256 "60e31d7d702449e0ba942f660d095b8fd04b6e3d37d6fa0fb4ab7d794a375ae9"

        def install
          bin.install "conf"
        end
      end
    end
  end
end
